name: hybrid-vqe
channels: 
  - conda-forge
  - defaults
dependencies: 
  - python=3.11
  - qiskit
  - pybind11
  - mpi4py
  - mpich
  - cupy
  - cmake
  - pip
  - numpy
  - scipy
  - matplotlib 
  - pip:
      - qiskit>=1.0.0
      - qiskit-aer>=0.14.0
      - qiskit-algorithms>=0.3.0
      - qiskit-nature
      - pylatexenc  
      - pyscf

